ci:
  autoupdate_commit_msg: 'chore: update pre-commit hooks'
  autofix_commit_msg: 'style: pre-commit fixes'
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: fa505ab9c3e0fedafe1709fd7ac2b5f8996c670d  # frozen: 26.3.1
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 5e2fb545eba1ea9dc051f6f962d52fe8f76a9794  # frozen: v0.15.13
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes]

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: 4380fbb73a154b5f5624794c1c78d9719ccc860f  # frozen: v2.16.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]
      - id: pretty-format-yaml
        args: [--autofix, --indent, '2', --offset, '2']

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: a4727cbbcd26d7098e96b9cb738169b59711ae51  # frozen: v1.24.1
    hooks:
      - id: zizmor
        files: ^\.github
        args: [--persona=pendantic]
