version: 2

sphinx:
  configuration: docs-sphinx/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: '3.8'

python:
  install:
    - requirements: docs-sphinx/requirements.txt
    - method: pip
      path: .
