version: 2

sphinx:
  configuration: docs-sphinx/conf.py

build:
  os: ubuntu-22.04

python:
  version: 3.7
  install:
    - requirements: docs-sphinx/requirements.txt
    - method: pip
      path: .
