name: Build sdist and wheel

on:
  # Run on demand with workflow dispatch
  workflow_dispatch:
  # Use from other workflows
  workflow_call:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-build-distributions
  cancel-in-progress: true
jobs:
  dist:
    name: Build distribution artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: hynek/build-and-inspect-python-package@2abe76da66d0a6a4a227101f9348ee855797cfa5 # v3.0.1
