name: Build sdist and wheel

on:
  # Run on demand with workflow dispatch
  workflow_dispatch:
  # Use from other workflows
  workflow_call:

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: hynek/build-and-inspect-python-package@d44ca7d91762de7a7d5436ddae667c6da6d1c3df # v2.18.0
